name: KlokanStorage

description:

permalink: pretty

sass:
  style: :compressed

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"

baseurl: "http://www.klokanstorage.com/"
