name: IIIFHosting

description:

permalink: pretty

sass:
  style: :compressed
  sass_dir: styles/_sass
  
exclude:
  - styles/base.scss

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"

baseurl: "http://www.iiifhosting.com/"
